### ISSUE TITLE
XPath context with default namespace?

### ISSUE THREAD

**Issue by vrurg** [libxml-raku/LibXML-raku#104]
Is it generally possible to register a namespace on XPath context with no prefix? Taking an SVG, for example:

```
my LibXML::XPath::Context $xc .= new: :node($svg);
$xc.registerNs(Str, $svg.namespaceURI);
$xc.findnodes('//g[@id="surface1"]').elems > 0; # True
```

Because currently the only way to get it working is to:

```
$xc.registerNs("svg", $svg.namespaceURI);
$xc.findnodes('//svg:g[@id="surface1"]').elems > 0; # True
```

I tried to remove definedness from `registerNS` prefix parameter, but then it fails deeper in `libxml2` itself.

An example of what's expected couldbe IntelliJ XPathView+XSLT plugin where it automatically picks up the default NS for its context.

**Comment by dwarring** [comment]
LibXML doesn't seem to have any way of setting a default namespace for XPath queries.

I'm guessing that IntelliJ is using the [javax.xml.xpath `setNamespaceContext()`](https://www.tabnine.com/code/java/methods/javax.xml.xpath.XPath/setNamespaceContext) method.

I agree that it'd be nice to have. But I think it'd need to be implemented in libxml2.

**Comment by vrurg** [comment]
Ok, no sense to have this opened then. 

Thank you!
