### ISSUE TITLE
[Windows10]: doesn't install 

### ISSUE THREAD

**Issue by AntonOks** [libxml-raku/LibXML-raku#113]
PS C:\Temp>
λ zef install LibXML
===> Searching for: LibXML
===> Searching for missing dependencies: Method::Also, W3C::DOM:ver<0.0.2+>
===> Building: LibXML:ver<0.10.9>:auth<zef:dwarring>:api<0.10.0>
[LibXML] Using prebuilt DLLs on Windows
[LibXML] Using prebuilt DLLs on Windows
===> Building [OK] for LibXML:ver<0.10.9>:auth<zef:dwarring>:api<0.10.0>
===> Staging Method::Also:ver<0.0.8>:auth<zef:lizmat>
===> Staging [OK] for Method::Also:ver<0.0.8>:auth<zef:lizmat>
===> Staging W3C::DOM:ver<0.0.3>:auth<zef:dwarring>
===> Staging [OK] for W3C::DOM:ver<0.0.3>:auth<zef:dwarring>
===> Staging LibXML:ver<0.10.9>:auth<zef:dwarring>:api<0.10.0>
installing: C:\Users\<user>\AppData\Local\Temp/raku-libxml-0.10.9/libxml2.dll
installing: C:\Users\<user>\AppData\Local\Temp/raku-libxml-0.10.9/xml6.dll
===> Staging [OK] for LibXML:ver<0.10.9>:auth<zef:dwarring>:api<0.10.0>
===> Testing: Method::Also:ver<0.0.8>:auth<zef:lizmat>
[Method::Also] ===SORRY!=== Error while compiling C:\Users\<user>\AppData\Local\Temp\.zef\1717484306.17720\3a049392fd66e814f71522a197a5389c52eda0
[Method::Also] 60.tar.gz\Method-Also-0.0.8/t\01-basic.t
[Method::Also] Type check failed in binding to parameter '$repo-id'; expected Str but got CompUnit::Repository::Spec
[Method::Also] (CompUnit::Repository...)
[Method::Also] at C:\Users\<user>\AppData\Local\Temp\.zef\1717484306.17720\3a049392fd66e814f71522a197a
[Method::Also] 5389c52eda060.tar.gz\Method-Also-0.0.8/t\01-basic.t:2
===> Testing [FAIL]: Method::Also:ver<0.0.8>:auth<zef:lizmat>
Aborting due to test failure: Method::Also:ver<0.0.8>:auth<zef:lizmat> (use --force-test to override)

λ raku -v
Welcome to Rakudo™ Star v2024.05.
Implementing the Raku® Programming Language v6.d.
Built on MoarVM version 2024.05.

λ zef -version
0.22.0

**Comment by dwarring** [comment]
There's a weird failure installing `Method::Also` as a dependency.

What happens, if you first try `$ zef install Method::Also`?

**Comment by AntonOks** [comment]
seems to be `zef` related, see discussion in https://github.com/lizmat/Method-Also/issues/5
