### ISSUE TITLE
performance

### ISSUE THREAD

**Issue by bo-tato** [libxml-raku/LibXML-raku#115]
For a script to parse a html page and do an xpath query, it's about 7x slower than `use XML::LibXML:from<Perl5>`.
[script with raku libxml2 bindings](https://gist.github.com/bo-tato/fe8194f53be5061a43af5264a8ec3f66)
[script in raku but with inline perl5 libxml2 bindings](https://gist.github.com/bo-tato/5b83080b9318b698877c53e543b71bf9)
It's about the same time difference if you leave off the xpath query and just parse the document.

**Comment by dwarring** [comment]
The Perl example is fetching strings, while the Raku example has the much greater overhead of fetching sets of stantiated text objects.

**Comment by bo-tato** [comment]
ah interesting, you mean change `say $node<text()>` to `say $node.to-literal`?
It makes it faster, now taking 48 seconds instead of 60 for 1500 iterations. Still if we remove all xpath code, and just  time `my LibXML::Document $doc .=  parse: :html, :recover, :suppress-errors, :string($html);` vs `XML::LibXML.load_html(recover => 1, suppress_errors => 1, string => $html)` it is 43 seconds vs 7.8, so a little better but still a big difference

**Comment by dwarring** [comment]
FWIW, for maximum throughput I'd write the LibXML example something like:
```
use HTTP::UserAgent;
use LibXML;
use LibXML::Document;
use LibXML::Node;

my $ua = HTTP::UserAgent.new;

my $html = $ua.get('https://nokogiri.org/tutorials/installing_nokogiri.html').content;

my $start-time = now;

say .to-literal for (^1500).hyper.map: {
    my LibXML::Document $doc .= parse: :html, :recover, :suppress-errors, :string($html);
    $doc.findnodes('//article//h2').Slip;
}

$*ERR.say: "done in: {now - $start-time} seconds";
```

**Comment by bo-tato** [comment]
ok thanks, I left off hyper just to make it easier to compare time on different languages. For reference the same script on my computer using libxml2 from ruby was 10 seconds, python 8, and crystal 6.5, so them and raku with inline perl5 are all about the same

**Comment by dwarring** [comment]
On my machine, I get about a 5x improvement, (28 secs -> 5secs)  if throw away LibXML::Parser::Context, and create a low-level `htmlMemoryParserCtxt` native parser directly, as below:

```raku
use HTTP::UserAgent;
use LibXML::Document;
use LibXML::Raw;
use LibXML::Config;
use LibXML::Enums;

my $ua = HTTP::UserAgent.new;

my $html = $ua.get('https://nokogiri.org/tutorials/installing_nokogiri.html').content;

my $start-time = now;

my $opts = LibXML::Config.parser-flags +| XML_PARSE_NOERROR;

for (^1500) {
    my htmlMemoryParserCtxt $ctx .= new: :string($html);
    $ctx.UseOptions: $opts;
    $ctx.ParseDocument;
    my xmlDoc:D $raw = $ctx.myDoc;
    my LibXML::Document $doc .= box($raw);
    say .to-literal for $doc.findnodes('//article//h2');
}

$*ERR.say: "done in: {now - $start-time} seconds";
```

This is what's happening under the hood, but the `LibXML::ParserContext` layer is adding a lot of overhead.

**Comment by bo-tato** [comment]
thanks, I get the same speedup with that version, but on maybe 15% of runs I get the exception:
```
Cannot unbox a type object (NativeCall::Types::Pointer) to an unsigned int.
  in method init-local-error-handling at /home/user/rakudo/share/perl6/site/sources/39220F748A6D133E88EE7FA4658F1D6891C8A476 (LibXML::ErrorHandling) line 222
  in submethod TWEAK at /home/user/rakudo/share/perl6/site/sources/630B47B30ED9133765A7F6506BDC165B344EA20D (LibXML::XPath::Context) line 151
  in method create at /home/user/rakudo/share/perl6/site/sources/3C4A7CA01ECFD5F84ED55E82AAF44C52BCFA7708 (LibXML::_Configurable) line 16
  in method xpath-context at /home/user/rakudo/share/perl6/site/sources/E33D8CD27A0BA050C164674B9185C781242B9152 (LibXML::Node) line 542
  in method findnodes at /home/user/rakudo/share/perl6/site/sources/E33D8CD27A0BA050C164674B9185C781242B9152 (LibXML::Node) line 546
  in block <unit> at raku-libxml-lowlevel.raku line 15
```

**Comment by dwarring** [comment]
Slows when I add error handling back in. Seems the error handling is still called even with the `:suppress-errors` option. 

```raku
use HTTP::UserAgent;
use LibXML::Document;
use LibXML::Raw;
use LibXML::Config;
use LibXML::Enums;

my $ua = HTTP::UserAgent.new;

my $html = $ua.get('https://nokogiri.org/tutorials/installing_nokogiri.html').content;

my $start-time = now;

my $opts = LibXML::Config.parser-flags +| XML_PARSE_NOERROR;

my $error-count;

for (^1500) {
    my htmlMemoryParserCtxt $ctx .= new: :string($html);
    $ctx.UseOptions: $opts;
    $ctx.ParseDocument;
    my xmlDoc:D $raw = $ctx.myDoc;
    $ctx.SetStructuredErrorFunc: -> $, $ {$error-count++};
    my LibXML::Document $doc .= box($raw);
    say .to-literal for $doc.findnodes('//article//h2');
}

$*ERR.say: "error-count: $error-count";
$*ERR.say: "done in: {now - $start-time} seconds";
````

```
error-count: 62958
done in: 5.364376408 seconds
```

The errors are being fully processed by the Raku handler before being thrown away by libxml2, thus slowing things down.

**Comment by dwarring** [comment]
^^ That commit fixes error handler to completely ignore errors with the `:suppress-errors` option is used.

**Comment by bo-tato** [comment]
thanks, the high-level code is now running for me in 12 seconds, comparable to other libxml2 bindings
