### ISSUE TITLE
findnodes errors with `XPath error : XML_XPATH_INVALID_OPERAND`

### ISSUE THREAD

**Issue by leedo** [libxml-raku/LibXML-raku#25]
I am porting a perl5 script that uses `XML::LibXML` to perl6 and encountered this error with the `findnodes` method. It seems to work in the perl5 version, so I'm wondering if it is an issue with the new perl6 implementation.

Here is a perl5 script:
```perl
#!/usr/bin/env perl

use strict;
use warnings;

use XML::LibXML;
use Test::More;

my $html = <<HTML;
<!DOCTYPE html>
<html>
<body>
<aside class="hello">hello</aside>
<nav>goodbye</nav>
</body>
</html>
HTML

my $parser = XML::LibXML->new;
my $doc = $parser->load_html(
    string => $html,
    recover => 2,
);

isa_ok $doc, 'XML::LibXML::Document';

my @nodes = $doc->findnodes("//aside[\@class='hello']");
ok @nodes > 0;

done_testing;
```
It passes. The perl6 version:

```perl6
#!/usr/bin/env perl6

use v6;
use LibXML;
use Test;

my $html = q:to/HTML/;
<!DOCTYPE html>
<html>
<body>
<aside class="hello">hello</aside>
<nav>goodbye</nav>
</body>
</html>
HTML

my $parser = LibXML.new;
my $doc = $parser.parse(
    :string($html),
    :recover,
    :suppress-errors,
    :suppress-warnings,
    :html
);

isa-ok $doc, 'LibXML::Document';

my @nodes = $doc.findnodes("//aside[@class='hello']");
ok @nodes > 0;
```

Fails with:

```
ok 1 - The object is-a '"LibXML::Document"'
XPath error : XML_XPATH_INVALID_OPERAND
  in block  at /Users/laylward/local/share/perl6/site/sources/4E263A1FB7C5CA5C54CC65071E474B21304F64B5 (LibXML::ErrorHandling) line 161
  in method flush-errors at /Users/laylward/local/share/perl6/site/sources/4E263A1FB7C5CA5C54CC65071E474B21304F64B5 (LibXML::ErrorHandling) line 141
  in method find at /Users/laylward/local/share/perl6/site/sources/28EB177FE770AAE0C55B2E0195B428F33FC911A0 (LibXML::XPath::Context) line 49
  in method findnodes at /Users/laylward/local/share/perl6/site/sources/28EB177FE770AAE0C55B2E0195B428F33FC911A0 (LibXML::XPath::Context) line 58
  in block <unit> at test.pl line 28
```

From my limited testing the xpath expression gives this error any time there are brackets (`[]`) in it.

I'm using the MacOS system version of libxml2
```
$ perl6 -MLibXML -e 'say LibXML.version'
v2.09.04
```
And I'm using the [latest master](https://github.com/p6-xml/LibXML-p6/commit/f1be0fb208221d89308a865dc5e33dcd299861ce) version of the LibXML perl6 module.

**Comment by leedo** [comment]
I believe my perl5 version of XML::LibXML was actually installed with another version of libxml2. When I attempt to install it with the system version it warns of a buggy version and incompatibilities. So I think you can probably ignore this, but I'll try to update if I figure it out.

**Comment by dwarring** [comment]
Thanks @leedo,
^^ That's an incidental commit was to get the `findnodes()` error handling the same as Perl 5. It now recovers, any time a value has been returned, throws an error otherwise.

Does it work for you to set the environment variable LD_LIBRARY_PATH=/usr/local/Cellar/libxml2/2.9.9_2/lib/ ?

**Comment by leedo** [comment]
That does seem to fix it. Thanks!

**Comment by dwarring** [comment]
^^ Changed these from constants to variables, just to make it easier to fix library paths if needed. Can now do:
    use LibXML::Native::Defs :$XML2; $XML2 =  '/usr/local/Cellar/libxml2/2.9.9_2/lib/libxml2.dylib';
