### ISSUE TITLE
Rakudo making hard work of dynamic load in box-class()

### ISSUE THREAD

**Issue by dwarring** [libxml-raku/LibXML-raku#27]
t/00ast.t seems sluggish on repeat requires of LibXML::Document via box-class().

Also seeing regular CI failures in 90threads.t that could be indicative of a lack of thread saftey in this class. E.g. https://travis-ci.org/p6-xml/LibXML-p6/jobs/607308000

inclined to cache to avoid repeated loading and possibly locking while loading.

**Comment by dwarring** [comment]
^^ Seems that t/00ast.t runs in about half the time (after precompilation)

**Comment by markldevine** [comment]
I made https://github.com/markldevine/raku-Hypervisor-IBM-POWER-HMC-REST using XML, and when I tried to fully convert to LibXML, I ran into longer run times (4-6 x) when snipping off branches, taking info from LibXML::Element objects and putting them in Raku object attributes.

I didn't have time to pin it down back then, for which I apologize.  But I wonder if I should try again after this fix.  Do you suspect that this could cause significant delays when snipping 50,000 values from a 10 MB XML?

**Comment by dwarring** [comment]
Hi @markldevine 
I've starting doing some bench-marking with #38. At this stage there seems to be only a moderate improvement in getElementsByTagName()  and other similar methods, since LibXML 0.1.7. I'd say hang off for the moment.

**Comment by dwarring** [comment]
@markldevine 
#38 completed.
There's been several improvements, including taking XPath out of getElementsbyXxx() methods and converting DOM classes to CPointer representations. 
Uploaded LibXML 0.5.0 to CPAN. Hopefully several times faster.

**Comment by markldevine** [comment]
David,



I am not a career developer (more a SysAdmin) & I don’t have years of wisdom in elegant ways to read/extract XML.  To make Raku tools, I simply look at the fine work developers have provided and infer heavily.



I seek your guidance as to which LibXML mechanics to employ to read a 10 MB XML file from disk, traverse/read every node, and load their values into a corresponding hierarchy of Raku objects/attributes.



It might seem smarter to create the corresponding hierarchy/classes dynamically using MOP mechanics, but there is a reason to have the complete hierarchy statically coded in rakumods.  So, I wrote a zillion lines of classes/rakumods with every value intuitively accessible to my consumers.



My requirement is to open the 10 MB XML file from disk and traverse it with the least amount of overhead or unnecessary work.  I see lots of mechanics to choose from, as of 06/18/2020.



Between DOM or SAX parsers, I can go big on memory, and slurping it all in as fast as possible is the priority. So, I infer DOM mechanics are called for here.



  1.  When I read the 10 MB file from disk, is it most efficient to:


my LibXML::Document $dom;

$dom = LibXML.parse(
    location => $file-or-url,
    :$html, :$URI, :$enc,
    # parser options ...
  );



or



my LibXML::Document $dom;



$dom = LibXML.parse(

    io => $raku-path-or-file-handle,

    :$html, :$URI, :$enc,

    # parser options ...

  );



…?  Or would LibXML::Reader be more advantageous for my purposes?  Or something else?



  1.  For speed, once I have a LibXML::Document $dom, should I implement the following or is there a better way?  Perhaps process .children attributes instead?



my LibXML::Element @nodes = $dom.getElementsByTagName('*');

for @nodes -> $node {

    # walk the hierarchy horizontally & vertically, loading all my *.rakumod objects/attributes…

}



  1.  To read from what I suspect is a text node, LibXML::Element @nodes, what is the most elegant way to:



if @nodes[0].can('nodes') && @nodes[0].nodes.elems && @nodes[0].nodes[0].textContent {

    return @nodes[0].nodes[0].textContent.trim if @nodes[0].nodes[0].elems == 1;



…?  How best to check if a text node has content without accidentally running into an exception?  Speed is important.





I can’t tell if I’m on track or out on a tangent.  I should be able to infer how to go forward with just a couple of helpful hints.



Thanks,



Mark Devine

mark@markdevine.com<mailto:mark@markdevine.com>

202-878-1500

**Comment by markldevine** [comment]
David,

This isn’t perfectly matched up, but you can see the improvement of LibXML 0.5.0 on the surface.  Now I have an App!!!  LibXML makes all the difference.  Much appreciation.  I’m going to merge now and go with LibXML in perpetuity.

XML
LibXML < .0.5
LibXML >= 0.5.0
HMC
INITIALIZE:
1.046
HMC
INITIALIZE:
2.156
HMC
INITIALIZE:
2.677
ManagedSystems
FETCH:
0.023
ManagedSystems
FETCH:
0.028
ManagedSystems
FETCH:
0.035
ManagedSystems
PARSE:
16.634
ManagedSystems
PARSE:
0.075
ManagedSystems
PARSE:
0.078
ManagedSystem
LOAD:
0.146
ManagedSystem
LOAD:
0.512
ManagedSystem
LOAD:
0.23
ManagedSystem
INITIALIZE:
2.926
ManagedSystem
INITIALIZE:
34.446
ManagedSystem
INITIALIZE:
6.128
ManagedSystem
LOAD:
0.089
ManagedSystem
LOAD:
0.31
ManagedSystem
LOAD:
0.149
ManagedSystem
INITIALIZE:
2.968
ManagedSystem
INITIALIZE:
36.158
ManagedSystem
INITIALIZE:
6.304
ManagedSystem
LOAD:
0.127
ManagedSystem
LOAD:
0.3
ManagedSystem
LOAD:
0.095
ManagedSystem
INITIALIZE:
3.056
ManagedSystem
INITIALIZE:
36.344
ManagedSystem
INITIALIZE:
6.359
ManagedSystem
LOAD:
0.1
ManagedSystem
LOAD:
0.258
ManagedSystem
LOAD:
0.107
ManagedSystem
INITIALIZE:
3.965
ManagedSystem
INITIALIZE:
61.167
ManagedSystem
INITIALIZE:
8.01
ManagedSystems
LOAD:
0.003
ManagedSystems
LOAD:
0
ManagedSystems
LOAD:
0.003
ManagedSystems
INITIALIZE:
20.677
ManagedSystems
INITIALIZE:
168.298
ManagedSystems
INITIALIZE:
8.195
LogicalPartitions
FETCH:
0.005
LogicalPartitions
FETCH:
0.005
LogicalPartitions
FETCH:
0.005
LogicalPartitions
FETCH:
0.019
LogicalPartitions
PARSE:
0.005
LogicalPartitions
PARSE:
0.006
LogicalPartitions
FETCH:
0.031
LogicalPartitions
LOAD:
0.004
LogicalPartitions
FETCH:
0.018
LogicalPartitions
FETCH:
0.043
LogicalPartitions
INITIALIZE:
6.734
LogicalPartitions
PARSE:
0.01
LogicalPartitions
PARSE:
0.757
LogicalPartitions
FETCH:
0.016
LogicalPartitions
FETCH:
0.032
LogicalPartitions
LOAD:
0.013
LogicalPartitions
PARSE:
0.01
LogicalPartitions
FETCH:
0.05
LogicalPartitions
INITIALIZE:
1.198
LogicalPartitions
LOAD:
0.007
LogicalPartitions
PARSE:
0.024
LogicalPartitions
PARSE:
1.653
LogicalPartitions
INITIALIZE:
11.545
LogicalPartitions
PARSE:
0.012
LogicalPartitions
PARSE:
2.227
LogicalPartitions
FETCH:
0.005
LogicalPartitions
LOAD:
0.006
LogicalPartitions
PARSE:
2.356
LogicalPartitions
PARSE:
0.014
LogicalPartitions
INITIALIZE:
1.172
LogicalPartitions
LOAD:
0.003
LogicalPartitions
LOAD:
0.007
LogicalPartitions
LOAD:
0.008
LogicalPartitions
LOAD:
0.003
LogicalPartitions
INITIALIZE:
11.861
LogicalPartitions
INITIALIZE:
1.175
LogicalPartitions
INITIALIZE:
2.713
LogicalPartitions
FETCH:
0.005
LogicalPartitions
LOAD:
0.004
LogicalPartitions
INITIALIZE:
2.714
LogicalPartitions
PARSE:
0.005
LogicalPartitions
INITIALIZE:
1.313
LogicalPartitions
LOAD:
0.005
LogicalPartitions
LOAD:
0.006
LogicalPartitions
LOAD:
0.004
LogicalPartitions
INITIALIZE:
2.834
LogicalPartitions
INITIALIZE:
10.02
LogicalPartitions
INITIALIZE:
1.37
VirtualIOServers
FETCH:
0.005
VirtualIOServers
FETCH:
0.005
VirtualIOServers
FETCH:
0.005
VirtualIOServers
FETCH:
0.012
VirtualIOServers
PARSE:
0.016
VirtualIOServers
FETCH:
0.01
VirtualIOServers
FETCH:
0.026
VirtualIOServers
LOAD:
0.002
VirtualIOServers
FETCH:
0.016
VirtualIOServers
FETCH:
0.042
VirtualIOServers
INITIALIZE:
16.857
VirtualIOServers
FETCH:
0.022
VirtualIOServers
PARSE:
2.049
VirtualIOServers
FETCH:
0.005
VirtualIOServers
PARSE:
0.154
VirtualIOServers
LOAD:
0.014
VirtualIOServers
PARSE:
0.011
VirtualIOServers
PARSE:
0.189
VirtualIOServers
INITIALIZE:
3.434
VirtualIOServers
LOAD:
0.002
VirtualIOServers
PARSE:
0.201
VirtualIOServers
PARSE:
3.614
VirtualIOServers
INITIALIZE:
26.151
VirtualIOServers
PARSE:
0.205
VirtualIOServers
PARSE:
3.89
VirtualIOServers
FETCH:
0.005
VirtualIOServers
LOAD:
0.004
VirtualIOServers
PARSE:
4.669
VirtualIOServers
PARSE:
0.016
VirtualIOServers
INITIALIZE:
2.36
VirtualIOServers
LOAD:
0.001
VirtualIOServers
LOAD:
0.002
VirtualIOServers
LOAD:
0.002
VirtualIOServers
INITIALIZE:
5.394
VirtualIOServers
INITIALIZE:
26.849
VirtualIOServers
INITIALIZE:
3.082
VirtualIOServers
LOAD:
0.017
VirtualIOServers
FETCH:
0.005
VirtualIOServers
LOAD:
0.001
VirtualIOServers
INITIALIZE:
5.731
VirtualIOServers
PARSE:
0.016
VirtualIOServers
INITIALIZE:
3.339
VirtualIOServers
LOAD:
0.002
VirtualIOServers
LOAD:
0.002
VirtualIOServers
LOAD:
0.001
VirtualIOServers
INITIALIZE:
5.885
VirtualIOServers
INITIALIZE:
22.351
VirtualIOServers
INITIALIZE:
3.384

Thanks,

Mark Devine
202/878-1500

**Comment by dwarring** [comment]
Hi Mark,
Glad it's working faster for you.  I think parse(:$io) might be slightly
fast than parse(:$location) but there wont be much in it.

The .parse(:!blanks) could be very handy for your processing of text nodes.
This eliminates all blank nodes, so you don't need to filter them. I think
you end up with just one text-node per leaf element.

I'm not sure if it fits your application, but I'll mention the find()
method.  You select leaf elements that contain text directly with an XPath
query. for example:

my LibXML::Element @elems = $dom = $dom.find("//*[text()]");

This is working bottom-up. For example @elems[0].parent will give you the
first elements parent;

Or you could start a level down and get the text nodes.

my LibXML::Text @text = $dom.find("//text()");

 For example @text[0].parent will give you the element that contains the
text.

Let me know what you think.
- David
