### ISSUE TITLE
Install error on Fedora 32

### ISSUE THREAD

**Issue by wayland** [libxml-raku/LibXML-raku#46]
I'm on Fedora 32.  

I ran:

$ sudo dnf install libxml2-devel.x86_64

...and that worked fine.  But then I got this failure:

$ zef install LibXML
===> Searching for: LibXML
===> Searching for missing dependencies: XML, Method::Also, File::Temp, LibraryMake, Pod::To::Markdown
===> Searching for missing dependencies: File::Directory::Tree, Pod::To::HTML:auth<github:Raku>
===> Searching for missing dependencies: Template::Mustache, Pod::Load:ver<0.4.0+>, Test::Output
===> Searching for missing dependencies: JSON::Fast, Test::META
===> Searching for missing dependencies: META6, License::SPDX
===> Searching for missing dependencies: JSON::Class:ver<0.0.14+>, JSON::Class:ver<0.0.5+>
===> Searching for missing dependencies: JSON::Marshal:ver<0.0.18+>, JSON::Unmarshal:ver<0.08+>
===> Searching for missing dependencies: JSON::Name
===> Building: LibXML:ver<0.5.9>:auth<cpan:WARRINGD>
[LibXML] src/dom.c: In function ‘domGenNsPrefix’:
[LibXML] src/dom.c:1964:27: warning: passing argument 2 of ‘xmlHashFree’ from incompatible pointer type [-Wincompatible-pointer-types]
[LibXML]  1964 |         xmlHashFree(hash, _domNullDeallocator);
[LibXML]       |                           ^~~~~~~~~~~~~~~~~~~
[LibXML]       |                           |
[LibXML]       |                           void (*)(void *, unsigned char *)
[LibXML] In file included from /usr/include/libxml2/libxml/parser.h:18,
[LibXML]                  from /usr/include/libxml2/libxml/globals.h:18,
[LibXML]                  from /usr/include/libxml2/libxml/threads.h:35,
[LibXML]                  from /usr/include/libxml2/libxml/xmlmemory.h:218,
[LibXML]                  from /usr/include/libxml2/libxml/tree.h:1307,
[LibXML]                  from src/dom.h:17,
[LibXML]                  from src/dom.c:10:
[LibXML] /usr/include/libxml2/libxml/hash.h:113:26: note: expected ‘xmlHashDeallocator’ {aka ‘void (*)(void *, const unsigned char *)’} but argument is of type ‘void (*)(void *, unsigned char *)’
[LibXML]   113 |       xmlHashDeallocator f);
[LibXML]       |       ~~~~~~~~~~~~~~~~~~~^
[LibXML] src/domXPath.c: In function ‘domUnreferenceNodeSet’:
[LibXML] src/domXPath.c:388:23: warning: passing argument 2 of ‘xmlHashFree’ from incompatible pointer type [-Wincompatible-pointer-types]
[LibXML]   388 |     xmlHashFree(hash, _domNodeSetDeallocator);
[LibXML]       |                       ^~~~~~~~~~~~~~~~~~~~~~
[LibXML]       |                       |
[LibXML]       |                       void (*)(void *, unsigned char *)
[LibXML] In file included from src/domXPath.c:10:
[LibXML] /usr/include/libxml2/libxml/hash.h:113:26: note: expected ‘xmlHashDeallocator’ {aka ‘void (*)(void *, const unsigned char *)’} but argument is of type ‘void (*)(void *, unsigned char *)’
[LibXML]   113 |       xmlHashDeallocator f);
[LibXML]       |       ~~~~~~~~~~~~~~~~~~~^
===> Building [OK] for LibXML:ver<0.5.9>:auth<cpan:WARRINGD>
===> Testing: XML:ver<0.3.0>:auth<Timothy Totten>
===> Testing [OK] for XML:ver<0.3.0>:auth<Timothy Totten>
===> Testing: Method::Also:ver<0.0.5>:auth<cpan:ELIZABETH>
===> Testing [OK] for Method::Also:ver<0.0.5>:auth<cpan:ELIZABETH>
===> Testing: File::Directory::Tree:auth<labster>
===> Testing [OK] for File::Directory::Tree:auth<labster>
===> Testing: File::Temp:ver<0.0.8>
===> Testing [OK] for File::Temp:ver<0.0.8>
===> Testing: LibraryMake:ver<1.0.0>:auth<github:retupmoca>
[LibraryMake] /usr/bin/ld: cannot find -latomic_ops
[LibraryMake] /usr/bin/ld: cannot find -luv
[LibraryMake] collect2: error: ld returned 1 exit status
[LibraryMake] make: *** [Makefile:4: test] Error 1
[LibraryMake] The spawned command 'make' exited unsuccessfully (exit code: 2, signal: 0)
[LibraryMake]   in block <unit> at t/01-basic.t line 21
[LibraryMake] # You planned 8 tests, but ran 5
===> Testing [FAIL]: LibraryMake:ver<1.0.0>:auth<github:retupmoca>
Aborting due to test failure: LibraryMake:ver<1.0.0>:auth<github:retupmoca> (use --force-test to override)

If there's more info I can provide to help, let me know!

**Comment by dwarring** [comment]
@wayland @retupmoca
Failing in LibraryMake tests. Have raised a [LibraryMake issue](https://github.com/retupmoca/P6-LibraryMake/issues/28)

**Comment by wayland** [comment]
Discovery: if I run zef install LibraryMake.  It turns out there were some missing prerequisite C libraries, and installing them resolved the problem:

sudo dnf install libatomic_ops-devel libuv-devel

HTH.
