### ISSUE TITLE
LibXML installation failed on Arch linux system.

### ISSUE THREAD

**Issue by wbiker** [libxml-raku/LibXML-raku#50]
Hi unfortunately, installing of LibXML failed for me.
My system:
> uname -a
> Linux linuxboxhome 5.9.11-arch2-1 #1 SMP PREEMPT Sat, 28 Nov 2020 02:07:22 +0000 x86_64 GNU/Linux

Libxml2 was installed with
`pacman -S libxml2`

zef command and output:
> zef install LibXML
> ===> Searching for: LibXML
> ===> Updating cpan mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/cpan1.json
> ===> Updating p6c mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/p6c1.json
> ===> Updated p6c mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/p6c1.json
> ===> Updated cpan mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/cpan1.json
> ===> Searching for missing dependencies: Method::Also
> ===> Building: LibXML:ver<0.5.13>:auth<cpan:WARRINGD>
> [LibXML] src/domXPath.c: In function ‘domUnreferenceNodeSet’:
> [LibXML] src/domXPath.c:388:23: warning: passing argument 2 of ‘xmlHashFree’ from incompatible pointer type >[-Wincompatible-pointer-types]
> [LibXML]   388 |     xmlHashFree(hash, _domNodeSetDeallocator);
> [LibXML]       |                       ^~~~~~~~~~~~~~~~~~~~~~
> [LibXML]       |                       |
> [LibXML]       |                       void (*)(void *, unsigned char *)
> [LibXML] In file included from src/domXPath.c:10:
> [LibXML] /usr/include/libxml2/libxml/hash.h:113:26: note: expected ‘xmlHashDeallocator’ {aka ‘void (*)(void *, const unsigned char *)’} but argument is of type ‘void (*)(void *, unsigned char *)’
> [LibXML]   113 |       xmlHashDeallocator f);
> [LibXML]       |       ~~~~~~~~~~~~~~~~~~~^
> ===> Building [OK] for LibXML:ver<0.5.13>:auth<cpan:WARRINGD>
> ===> Testing: Method::Also:ver<0.0.5>:auth<cpan:ELIZABETH>
> ===> Testing [OK] for Method::Also:ver<0.0.5>:auth<cpan:ELIZABETH>
> ===> Testing: LibXML:ver<0.5.13>:auth<cpan:WARRINGD>
> [LibXML] # Running libxml2 version: 2.09.10 (module 0.5.13)
> [LibXML] Native call expected argument 3 with CStruct representation, but got a P6opaque (Scalar)
> [LibXML]   in method domInsertBefore at /home/wolf/.zef/store/LibXML-0.5.13.tar.gz/LibXML-0.5.13/.precomp> /9E716920394ADD07B5F95FCE4853BC2D91E0256B/0E/0E564D4A8FA7D04F9652FE88A765EF9CF5BAF289 line 1
> [LibXML]   in method insertBefore at /home/wolf/.zef/store/LibXML-0.5.13.tar.gz/LibXML-0.5.13/lib/LibXML/Raw/DOM/Node.rakumod (LibXML::Raw::DOM::Node) line 133
> [LibXML]   in method insertBefore at /home/wolf/.zef/store/LibXML-0.5.13.tar.gz/LibXML-0.5.13/lib/LibXML/Node.rakumod (LibXML::Node) line 499
> [LibXML]   in block  at t/04node.t line 174
> [LibXML]   in block <unit> at t/04node.t line 18
> [LibXML] # You planned 201 tests, but ran 70
> ===> Testing [FAIL]: LibXML:ver<0.5.13>:auth<cpan:WARRINGD>
> Aborting due to test failure: LibXML:ver<0.5.13>:auth<cpan:WARRINGD> (use --force-test to override)
> zef install LibXML  274.31s user 13.66s system 196% cpu 2:26.32 total

I hope that helps

**Comment by dwarring** [comment]
Oops didn't regress last release properly. Seeing that error when run against Rakudo 2019.11

**Comment by dwarring** [comment]
@wbiker,
I only tested last release against Rakudo 2012.12 and broke tests on Rakudo versions.

Please retry with LibXML 0.5.14, uploaded to CPAN which should pass on Rakudo 2019.11 onwards.

**Comment by wbiker** [comment]
Ups, forget to mention my Raku version 2020.09.
Anyways, with your updated version 0.5.14 tests and installation have worked!

Thank you!
