### ISSUE TITLE
LibXML::Reader type check fails on text nodes

### ISSUE THREAD

**Issue by avuserow** [libxml-raku/LibXML-raku#60]
I'm getting this error when trying to use the reader interface:

```
Type check failed for return value; expected LibXML::Types::QName but got Str ("#text")
  in sub MAIN at ratings.raku line 8
  in block <unit> at ratings.raku line 3
```

my script:
```
use LibXML::Reader;

sub MAIN(IO() $path) {
    my LibXML::Reader $reader .= new(file => $path.Str) or die "cannot read file.xml\n";
    while $reader.read {
        say $reader.name;
    }
}
```

simplified xml:
```
<foo>bar</foo>
```

Using `LibXML:ver<0.6.4>:auth<cpan:WARRINGD>` on Raku 2021.05.

Parsing using the regular interface works fine. Let me know if you need any other information.

**Comment by dwarring** [comment]
`name()` return type `QName` was too stringent. It can also return `#text`, `#comment` etc. Changed return to `Str`.

Also fixed a simillar issue in `localName()` method, changing return type `NCName`  to `Str`.

Fix uploaded to CPAN with LibXML 0.6.5.
