### ISSUE TITLE
Possible flappy test

### ISSUE THREAD

**Issue by jonathanstowe** [libxml-raku/LibXML-raku#62]
Hi,
When I did `zef install LibXML`  I got:

```
===> Testing: LibXML:ver<0.6.8>:auth<cpan:WARRINGD>
[LibXML] # Running libxml2 version: 2.09.12 (module 0.6.8)
[LibXML] corrupted size vs. prev_size while consolidating
===> Testing [FAIL]: LibXML:ver<0.6.8>:auth<cpan:WARRINGD>
Aborting due to test failure: LibXML:ver<0.6.8>:auth<cpan:WARRINGD> (use --force-test to override)
```

But of course when I re-ran it with `-v` to see which test it was it passed and installed OK.

So this is more of a headsup rather than an actionable issue :-D

**Comment by dwarring** [comment]
There's been some fixes to potential issues both in LibXML and Rakudo. Issue doesn't seem to have occurred for some time.
