### ISSUE TITLE
CI fails on alpine linux

### ISSUE THREAD

**Issue by melezhik** [libxml-raku/LibXML-raku#69]
Hi!

Here is the log - http://sparrowhub.io:2222/report/125 

Does it see xml library?

HTH

Aleksei

**Comment by dwarring** [comment]
As well as the libxml2 library itself, this module has some C bindings that need to be compiled by running `raku Build.pm6` or `zef build .`.

My first thought is that  Build.pm6 hasn't been run.  Has it?

However I'm also finding it a bit strange that NativeCall is trying to find `xml6.dll` on an alpine linux platform. I'd expect it to be looking for `xml6.so`.

**Comment by dwarring** [comment]
Note that Builld.pm6  `libxml2.dll` and `xml6.dll` are checked into `resources\libraries/` for use on Windows only.

Running`Build.pm6` does nothing on Windows, which uses there pre-built dlls. But it does need to be run on Linux to compile `xml6.so`.

**Comment by melezhik** [comment]
I see. Looks like it's because sparkyci only runs `racoco -l --html` (which int runs runs `zef test` ) skipping `zen build` stage - https://github.com/melezhik/sparkyci/blob/main/sparky/raku/sparrowfile#L103 ,
I wonder if `zef test` should call `zef build` as well? cc @ugexe @atroxaper

**Comment by melezhik** [comment]
> RunningBuild.pm6 does nothing on Windows,

And looks like now by default the installers looks for `*.dll` files, huh?

**Comment by melezhik** [comment]
It passes now. sparrowhub.io:2222/report/152

So “zef test” does not invoke “zef build” , right? Cc @ugexe

**Comment by dwarring** [comment]
alpine linux somehow fell back to a  DLL extension `Cannot locate native library '/home/raku/.sparky/projects/raku/.sparrowdo/scm/resources/libraries/xml6.dll'`

Fwiw, I triied to  by running `t/000sanity.t` from a clean git checkout of LibXML on Debian . Same failures, but with `.so` extension as expected.

```
$ raku -I . t/000sanity.t
ok 1 - libxml2 sanity
ok 2 - can call xmlInitParser()
not ok 3 - binding lib sanity
# Failed test 'binding lib sanity'
# at t/000sanity.t line 18
# Cannot locate native library '/home/david/git/LibXML-raku/resources/libraries/libxml6.so': /home/david/git/LibXML-raku/resources/libraries/libxml6.so: cannot open shared object file: No such file or directory
unable to access 'xml6' binding library; has it been built? (e.g. 'zef build .)
not ok 4 - /home/david/git/LibXML-raku/resources/libraries/libxml6.so xml6_doc_set_encoding symbol
# Failed test '/home/david/git/LibXML-raku/resources/libraries/libxml6.so xml6_doc_set_encoding symbol'
# at t/000sanity.t line 22
# error fetching xml6_doc_set_encoding symbol: Cannot locate native library '/home/david/git/LibXML-raku/resources/libraries/libxml6.so': /home/david/git/LibXML-raku/resources/libraries/libxml6.so: cannot open shared object file: No such file or directory
not ok 5 - /home/david/git/LibXML-raku/resources/libraries/libxml6.so xml6_gbl_set_tag_expansion symbol
# Failed test '/home/david/git/LibXML-raku/resources/libraries/libxml6.so xml6_gbl_set_tag_expansion symbol'
# at t/000sanity.t line 22
# error fetching xml6_gbl_set_tag_expansion symbol: Cannot locate native library '/home/david/git/LibXML-raku/resources/libraries/libxml6.so': /home/david/git/LibXML-raku/resources/libraries/libxml6.so: cannot open shared object file: No such file or directory
ok 6 - xml2 xmlBufferCreate binding
ok 7 - xml2 xmlNewDocNode binding
ok 8 - xml2 xmlParserVersion binding
ok 9 - xml2 xmlSaveNoEmptyTags binding
ok 10 - CLIB malloc binding
ok 11 - CLIB memcpy binding
ok 12 - CLIB free binding
1..12
# You failed 3 tests of 12
$ raku -v
Welcome to Rakudo™ v2022.03-221-gdcb0ac099.
Implementing the Raku® Programming Language v6.d.
Built on MoarVM version 2022.03-17-g794e1d589.
$ cat /etc/issue
Debian GNU/Linux 10 \n \l

$ 
```

**Comment by melezhik** [comment]
anyway, after adding `zef build .` test passes, I can close the issue. Probably fall back logic for alpine is out of the scope, right?

**Comment by dwarring** [comment]
Yes, its a minor secondary issue
